"""V_05__add_relationship_user_and_competition

Revision ID: 5377ec8eed31
Revises: 5f5e2299a0d3
Create Date: 2023-08-24 11:45:02.783132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5377ec8eed31"
down_revision: Union[str, None] = "5f5e2299a0d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
