"""V_06__update_relationship_user_and_competition

Revision ID: 64f7acba1016
Revises: 5377ec8eed31
Create Date: 2023-08-24 12:06:34.685949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f7acba1016'
down_revision: Union[str, None] = '5377ec8eed31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
