"""v_07__add_is_deleted_in_auth

Revision ID: 6bb0ad715496
Revises: 64f7acba1016
Create Date: 2023-08-25 09:51:33.795288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6bb0ad715496"
down_revision: Union[str, None] = "64f7acba1016"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auths", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auths", "is_deleted")
    # ### end Alembic commands ###
